from  datetime import datetime


class DriverLog:
    def __init__(self):
        self.logId= 2147483648
        self.vehicleId= 7111
        self.utc= "192948.999"
        self.latitude= "2104.2078S"
        self.latitude= "11607.0842E"
        self.state= "WA"
        self.postCode= ""
        self.state= "Mardie"
        self.distanceTravelled= 0.0000
        self.hdop= "1.2"
        self.altitude= "35"
        self.fix= "0"
        self.cog= "326"
        self.ppkm= "22.85"
        self.spkn= "0"
        self.nsat= "19"
        self.dateTime= datetime.now()
        self.date= datetime.now().date()
        self.transmit= "N"
        self.serverDateTime= datetime.now()
        self.tempVoltage= "13.8"
        self.streetAddress= ""
        self.postedLimit= "0"
        self.eventid= "6001"
        self.localDateTime= datetime.now()
        self.fuelLevel= 0
        self.rpm= 1436
        self.odometer= 118736.38
        self.kpl= 1.19
        self.bv= 13.80
        self.adc= 0.00
        self.hwOdometer= 512
        self.trueOdometer= 0.00
        self.sqlInsertDateTime= datetime.now()
        self.listenerDateTimeUTC= datetime.now()